#!/usr/bin/env python3

#  SPDX-License-Identifier: BSD-3-Clause
#
#  Copyright (c) 2021  LB3361
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the University nor the names of its contributors
#     may be used to endorse or promote products derived from this software
#     without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
#  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
#  FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
#  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
#  OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
#  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
#  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
#  OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
#  SUCH DAMAGE.

from __future__ import print_function
import sys

if sys.version_info < (3, 6):
    print('glcc: fatal error: python 3.6.0 or higher is required.')
    sys.exit(1)

import os, sys, json
import os.path as path

# locate progdir
progname = path.realpath(__file__)
progdir = path.dirname(progname)

# read rom data
roms = {}
romfile = path.join(progdir, 'roms.json')
if os.access(romfile, os.R_OK):
    with open(romfile) as file:
        roms = json.load(file)
else:
    printf("glcc: cannot access rom file %s" % romfile, file = sys.stderr)

# copy arguments
hascpu = False
hasrom = False
hasv = False
for arg in sys.argv:
    if arg.startswith('-cpu='):
        hascpu = True
    elif arg.startswith('-rom='):
        hasrom = True
    elif arg == '-v':
        hasv = True
if hascpu or not hasrom:
    argv = sys.argv
else:
    argv = []
    for arg in sys.argv:
        argv.append(arg)
        if arg.startswith('-rom='):
            rom = arg[5:]
            if not rom in roms:
                print("glcc: warning. unrecognized rom '%s'" % rom, file=sys.stderr)
            else:
                argv.append("-cpu=%d" % roms[rom]['cpu'])
        romarg = False

# find and exec lcc
lccname = path.join(progdir, "lcc")
if not os.access(lccname, os.X_OK):
   lccname = path.join(progdir, "lcc")
if not os.access(lccname, os.X_OK):
   print("glcc: fatal error: cannot find executable lcc in %s" % progdir, file=sys.stderr)
   sys:exit(1)
if hasv:
    argv[0] = lccname
    print(*argv, file=sys.stderr)
argv[0] = path.basename(lccname)
os.putenv("LCCDIR", progdir)
os.execv(lccname, argv)

# Local Variables:
# mode: python
# indent-tabs-mode: ()
# End:
