#!/usr/bin/env python3

from __future__ import print_function
import sys

if sys.version_info < (3, 6):
    print('glink: fatal error: python 3.6.0 or higher is required.')
    sys.exit(1)

from glink import *

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))

# Local Variables:
# mode: python
# indent-tabs-mode: ()
# End:


